from Header import *

date=str(input("Input date: "))
am=int(input("Input ammount of meetings: "))
lis=[]
print("Let`s begin with meetings:")
for i in range(am):
    print("Meeting ", i+1)
    A=str(input("PIB of person: "))
    S=str(input("Plase of meeting: "))
    D=str(input("Input time of begining (HH:MM): "))
    F=str(input("Input endurance of meeting (HH:MM): "))
    meet = Meeting(date, D, F, A, S)
    lis.append(meet)
print("Input info about birthday party:")
A=str(input("PIB of person: "))
S=str(input("Plase of the party: "))
D=str(input("Input time of begining (HH:MM): "))
F=str(input("Input endurance of the party (HH:MM): "))
O=int(input("Input age of person: "))
party = Birthday(date, D, F, A, S, O)
print("General info about the day:")
for i in range(am):
    print("Meeting ", i+1)
    print("PIB of person: ", lis[i].PIB, "\nPlace of meeting: ", lis[i].place, "\nDate of meeting: ", lis[i].dat)
    print("Time of begining: ", lis[i].in_t, "\nEndurance: ", lis[i].en)
print("Birthday party:")
print("PIB of person: ", party.PIB, "\nAge of person: ", party.age, "\nPlace of party: ", party.place, "\nDate of party: ", party.dat)
print("Time of begining: ", party.in_t, "\nEndurance: ", party.en)
posit=seek(lis, am)
print("Info about the last meeting:")
print("PIB of person: ", lis[posit].PIB, "\nPlace of meeting: ", lis[posit].place, "\nDate of meeting: ", lis[posit].dat)
print("Time of begining: ", lis[posit].in_t, "\nEndurance: ", lis[posit].en)
res=lis[posit].Last_calc(party.in_t)
print(res)